version : '3'

services: 
    web:
        # A bug forcing docker compose to quit when started
        stdin_open: true
        # forcing to pick the Dockerfile.dev
        build: 
            context : .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app    